//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BaoCao
    {
        public int ID { get; set; }

        [Display(Name ="Tuần")]
        public Nullable<int> Tuan { get; set; }

        [Display(Name ="Tên nhóm")]

        public Nullable<int> Nhom_ID { get; set; }

        [Display(Name = "Tiêu đề")]
        [Required(ErrorMessage ="Chưa nhập {0}")]
        public string TieuDe { get; set; }

        [Display(Name = "Nội dung")]
        [Required(ErrorMessage = "Chưa nhập {0}")]
        public string NoiDung { get; set; }

        [Display(Name = "Thời gian báo cáo")]
        public Nullable<System.DateTime> ThoiGianBaoCao { get; set; }

        [Display(Name = "File Upload")]
        [Required(ErrorMessage = "Chưa chọn {0}")]
        public string FileUpload { get; set; }


        public string FilePath { get; set; }

        [Display(Name = "Phản hồi")]
        public string PhanHoi { get; set; }
    
        public virtual Nhom Nhom { get; set; }
    }
}
