//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NguoiDung
    {
        public int ID { get; set; }

       
        public string TenDangNhap { get; set; }

       
        public string MatKhau { get; set; }

        [Display(Name = "Họ và tên")] 
        public string HoTen { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }
        public Nullable<int> Nhom_ID { get; set; }
        public Nullable<int> DeTai_ID { get; set; }
        public Nullable<int> ChucVu_ID { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual DeTai DeTai { get; set; }
        public virtual Nhom Nhom { get; set; }
    }
}
